更新方針1
hanwu85/WCA-TC-2023_Open pull request #1
Opened 2023-07-16 05:36 UTC by hanwu85

2023-07-16 07:04 UTC, richar983 requested changes
就是測試一下xDD

結果居然還刪不掉xDDDD

2023-07-16 07:10 UTC, richar983 commented
原文：

1h1+++) [ADDITION] Competitors may request to compete at a time different to the scheduled time for the round in a separate group. The WCA Delegate should carefully consider the fairness and practicality of the situation before approving any such requests, and must ensure that such attempts follow [Regulation 9l](regulations:regulation:9l) (i.e. they must start after all competitors have finished their attempts from any previous round of the same event, and finish before any competitor has started an attempt for any following round of the same event). Competitors requesting such accommodations should contact the organization team and WCA Delegate before the competition. Exception: such accommodations are not permitted for 3x3x3 Fewest Moves, which specifies its own limited accommodations in [Guideline E2b++](guidelines:guideline:E2b++).

2023-07-16 07:12 UTC, richar983 commented
原文：

!1h1+++) [ADDITION] Competitors may request to compete at a time different to the scheduled time for the round in a separate group. The WCA Delegate should carefully consider the fairness and practicality of the situation before approving any such requests, and must ensure that such attempts follow [Regulation 9l](regulations:regulation:9l) (i.e. they must start after all competitors have finished their attempts from any previous round of the same event, and finish before any competitor has started an attempt for any following round of the same event). Competitors requesting such accommodations should contact the organization team and WCA Delegate before the competition. Exception: such accommodations are not permitted for 3x3x3 Fewest Moves, which specifies its own limited accommodations in [Guideline E2b++](guidelines:guideline:E2b++).

2023-08-04 19:09 UTC, richar983 requested changes

2023-08-04 19:09 UTC, richar983 commented on wca-guidelines.md
> +- 1h+++) [附加] 參賽者可以要求在同一輪中，加入不同時間的參賽組別。在WCA代表的同意下，可以允許參賽者參賽。WCA代表應該謹慎考慮該要求的比賽公平性和實行的可行性，且必須要確保這個改變有符合[規則 9l](regulations:regulation:9l)(也就是說該參賽者必須要在同一項目的前一輪全部結束以及下一輪還未開始以前結束還原)。有該需求的參賽者應該在比賽前聯絡主辦團隊和W
原文：
`
1h1+++) [ADDITION] Competitors may request to compete at a time different to the scheduled time for the round in a separate group. The WCA Delegate should carefully consider the fairness and practicality of the situation before approving any such requests, and must ensure that such attempts follow [Regulation 9l](regulations:regulation:9l) (i.e. they must start after all competitors have finished their attempts from any previous round of the same event, and finish before any competitor has started an attempt for any following round of the same event). Competitors requesting such accommodations should contact the organization team and WCA Delegate before the competition. Exception: such accommodations are not permitted for 3x3x3 Fewest Moves, which specifies its own limited accommodations in [Guideline E2b++](guidelines:guideline:E2b++).
`

```suggestion
- 1h+++) [附加] 在WCA代表的同意下，參賽者可以要求在同一輪比賽中參加不同的組別。WCA代表應該謹慎考慮該要求對比賽的公平性與實行的可行性，且必須要確保這個更動有符合[規則 9l](regulations:regulation:9l)(也就是該參賽者必須要在同一項目的前一輪全部結束且下一輪還未開始以前結束還原)。有此需求的參賽者應該要在比賽前聯絡主辦團隊和WCA代表。例外：最少步數解不能使用這個安排因為 [指導方針 E2b++](guidelines:guideline:E2b++)中有獨自的安排方式。
```

2023-08-04 19:09 UTC, richar983 commented on wca-guidelines.md
> +- 1h+++) [附加] 參賽者可以要求在同一輪中，加入不同時間的參賽組別。在WCA代表的同意下，可以允許參賽者參賽。WCA代表應該謹慎考慮該要求的比賽公平性和實行的可行性，且必須要確保這個改變有符合[規則 9l](regulations:regulation:9l)(也就是說該參賽者必須要在同一項目的前一輪全部結束以及下一輪還未開始以前結束還原)。有該需求的參賽者應該在比賽前聯絡主辦團隊和W
```suggestion
- 1h+++) [附加] 在WCA代表的同意下，參賽者可以要求在同一輪比賽中參加不同的組別。WCA代表應該謹慎考慮該要求對比賽的公平性與實施的可行性，且必須要確保這個更動有符合[規則 9l](regulations:regulation:9l)(也就是該參賽者必須要在同一項目的前一輪全部結束且下一輪還未開始以前結束還原)。有此需求的參賽者應該要在比賽前聯絡主辦團隊和WCA代表。例外：最少步數解不能使用這個安排因為 [指導方針 E2b++](guidelines:guideline:E2b++)中有獨自的安排方式。
```

其中有幾個小地方可能值得探討看看…

`參加不同的組別` 或 `參加不同時間的組別`

`實行的可能性` 或 `實施的可能性`

2023-08-05 09:18 UTC, hanwu85 commented on wca-guidelines.md
> +- 1h+++) [附加] 參賽者可以要求在同一輪中，加入不同時間的參賽組別。在WCA代表的同意下，可以允許參賽者參賽。WCA代表應該謹慎考慮該要求的比賽公平性和實行的可行性，且必須要確保這個改變有符合[規則 9l](regulations:regulation:9l)(也就是說該參賽者必須要在同一項目的前一輪全部結束以及下一輪還未開始以前結束還原)。有該需求的參賽者應該在比賽前聯絡主辦團隊和W
`實行的可能性` 或 `實施的可能性` 這兩個我都OK
`參加不同的組別` 或 `參加不同時間的組別`  雖然不同組別通常都是不同時間，但我覺得還是要刻意強調一下是不同時間，畢竟原文也有寫"不同時間"

2023-08-05 09:19 UTC, hanwu85 commented on wca-guidelines.md
> +- 1h+++) [附加] 參賽者可以要求在同一輪中，加入不同時間的參賽組別。在WCA代表的同意下，可以允許參賽者參賽。WCA代表應該謹慎考慮該要求的比賽公平性和實行的可行性，且必須要確保這個改變有符合[規則 9l](regulations:regulation:9l)(也就是說該參賽者必須要在同一項目的前一輪全部結束以及下一輪還未開始以前結束還原)。有該需求的參賽者應該在比賽前聯絡主辦團隊和W
我的建議
```suggestion
- 1h+++) [附加] 在WCA代表的同意下，參賽者可以要求在同一輪比賽中參加不同時間的組別。WCA代表應該謹慎考慮該要求對比賽的公平性與實施的可行性，且必須要確保這個更動有符合[規則 9l](regulations:regulation:9l)(也就是該參賽者必須要在同一項目的前一輪全部結束且下一輪還未開始以前結束還原)。有此需求的參賽者應該要在比賽前聯絡主辦團隊和WCA代表。例外：最少步數解不能使用這個安排因為 [指導方針 E2b++](guidelines:guideline:E2b++)中有獨自的安排方式。
```

2023-08-05 19:00 UTC, richar983 approved these changes

2023-08-05 19:00 UTC, richar983 commented on wca-guidelines.md
> +- 1h+++) [附加] 參賽者可以要求在同一輪中，加入不同時間的參賽組別。在WCA代表的同意下，可以允許參賽者參賽。WCA代表應該謹慎考慮該要求的比賽公平性和實行的可行性，且必須要確保這個改變有符合[規則 9l](regulations:regulation:9l)(也就是說該參賽者必須要在同一項目的前一輪全部結束以及下一輪還未開始以前結束還原)。有該需求的參賽者應該在比賽前聯絡主辦團隊和W
看起來是挺不錯的！

2023-08-06 05:22 UTC, merged