更新方針A
hanwu85/WCA-TC-2023_Open pull request #11
Opened 2023-07-17 12:10 UTC by hanwu85

2023-07-19 19:12 UTC, richar983 requested changes

2023-07-19 19:12 UTC, richar983 commented on wca-guidelines.md
> +- A1a+) [釐清] 如果兩種時間限制都有適用，單次還原時間限制禁止大於總時間限制。
適用 > 使用 / 應用
禁止 > 不得 ??

```suggestion
- A1a+) [釐清] 如果兩種時間限制都有使用，單次還原時間限制不得大於總時間限制。
```
```suggestion
- A1a+) [釐清] 如果兩種時間限制都有應用，單次還原時間限制不得大於總時間限制。
```

2023-07-19 19:12 UTC, richar983 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪的比賽只有總時間限制是30分鐘，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三
```suggestion
- A1a2++) [舉例] 如果某一輪的比賽有總時間限制是30分鐘，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三次還原是13:59 + 2 = 14:01的時候則沒有符合時間限制。
```

口語修正

2023-07-19 19:12 UTC, richar983 commented on wca-guidelines.md
> +- A1a2++++) [舉例] 如果某一輪比賽有總時間限制20分鐘和單次時間限制8分鐘，且參賽者的頭兩次還原成績為 7:00 和 7:30，則第三次還原的時間限制為20:00 - 7:00 - 7:30 = 5:30和8:00中較短的時間，也就是5:30。
```suggestion
- A1a2++++) [舉例] 如果某一輪比賽有總時間限制20分鐘和單次時間限制8分鐘，且參賽者的前兩次還原成績為 7:00 和 7:30，則第三次還原的時間限制為 20:00 - 7:00 - 7:30 = 5:30 和 8:00 中較短的時間，也就是 5:30。
```

標註 xx:xx 的時候，或許統一前後有空格會比較好？

2023-07-19 19:12 UTC, richar983 commented on wca-guidelines.md
> +- A7g++++) [釐清] 一位參賽者可以在以下情況視為比賽經驗不足：在某一個比賽項目第一次參賽，或是相當長的時間沒有在某一個比賽項目參賽。意外事件必須要跟經驗不足有所關聯。
```suggestion
- A7g++++) [釐清] 一位參賽者可以在以下情況被視為比賽經驗不足：在某個比賽項目中第一次參賽、或很久沒有參加某個比賽項目。意外事件必須要跟經驗不足有所關聯。
```

這裡的修正我覺得需要討論

A. 某一個 / 某個
> 我不確定有這個部分使用的廣泛度有多大？但是考慮長篇文章的閱讀性，是否使用「某個」會好過「某一個」呢？儘管可能正式性有可能下降，但是可以避免有太多數字出現其中... ？

B. 範例中的兩個句子之間，用了「或」的情況下，是否應該要逗號，或是應該換成頓號？！

2023-07-19 19:12 UTC, richar983 commented on wca-guidelines.md
> +- A7g+) [舉例] 比賽經驗不足的參賽者可以因為以下情況獲得額外的還原機會：沒有等到計時器綠燈亮、不正確地啟動或停止計時器、由於不知道如何開始還原導致觀察超過時間、或其他有關還原流程的處罰。
```suggestion
- A7g+) [舉例] 比賽經驗不足的參賽者可以因為以下情況獲得額外的還原機會：沒有等到計時器綠燈亮、不正確地啟動或停止計時器、由於不知道如何開始還原導致超過觀察時間、或其他有關還原流程的處罰。
```

2023-07-23 10:55 UTC, hanwu85 commented on wca-guidelines.md
> +- A1a+) [釐清] 如果兩種時間限制都有適用，單次還原時間限制禁止大於總時間限制。
原文:
`If both limits are applied, the time limit per attempt must not be greater than the cumulative time limit.`

applied 翻譯錯誤，適用改成 `使用`

must not就是禁止 所以這個是這確的

2023-07-23 10:57 UTC, hanwu85 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪的比賽只有總時間限制是30分鐘，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三
原文: `If a round has only a cumulative time limit of 30 minutes and the competitor's results of the first two attempts are 6:00 and DNF (10:00), `

意思是說  "沒有單次的時間限制"  但是 "有總時間限制"

改成  `如果某一輪的比賽只使用總時間限制制度，設定為30分鐘`  如何?

2023-07-23 11:03 UTC, hanwu85 commented on wca-guidelines.md
> +- A7g++++) [釐清] 一位參賽者可以在以下情況視為比賽經驗不足：在某一個比賽項目第一次參賽，或是相當長的時間沒有在某一個比賽項目參賽。意外事件必須要跟經驗不足有所關聯。
某一個/某個  我都OK

記得或的話 是不用頓號的?

2023-08-03 14:50 UTC, richar983 requested changes

2023-08-03 14:50 UTC, richar983 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪的比賽只有總時間限制是30分鐘，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三
對，我理解原文的意思，不過中文如果不額外加括號的話，感覺好像會讓閱讀的人難以知道斷句在哪，以至於產生一些盲區。

或者 `如果某一輪比賽只使用了總時間限制為30分鐘的設置` 是否也可以考慮看看呢？

2023-08-03 14:50 UTC, richar983 commented on wca-guidelines.md
>  - A7g++++) [釐清] 一位參賽者可以在以下情況視為比賽經驗不足：在某一個比賽項目第一次參賽，或是相當長的時間沒有在某一個比賽項目參賽。意外事件必須要跟經驗不足有所關聯。
```suggestion
- A7g++++) [釐清] 一位參賽者在以下情況可以被視為比賽經驗不足：第一次參加某一個比賽項目，或是很長的時間沒有在某一個比賽項目參賽。意外事件必須要跟經驗不足有所關聯。
```

結果我今天又有新的想法了xDD
或許這樣子翻譯上感覺會更流暢？！


仔細想想，如果用上"或"，應該還是逗點好一點，是沒有或的時候才頓號。

2023-08-04 14:13 UTC, hanwu85 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪的比賽只有總時間限制是30分鐘，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三
```suggestion
- A1a2++) [舉例] 如果某一輪比賽只使用了總時間限制為30分鐘的設置，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三次還原是13:59 + 2 = 14:01的時候則沒有符合時間限制。
```

2023-08-04 14:13 UTC, hanwu85 commented on wca-guidelines.md
>  - A7g++++) [釐清] 一位參賽者可以在以下情況視為比賽經驗不足：在某一個比賽項目第一次參賽，或是相當長的時間沒有在某一個比賽項目參賽。意外事件必須要跟經驗不足有所關聯。
OK!

2023-08-04 19:18 UTC, richar983 approved these changes
A1a2++ 是否有更新到原檔中？Merge前可能要再確認一下…

2023-08-05 00:12 UTC, merged