更新方針B
hanwu85/WCA-TC-2023_Open pull request #13
Opened 2023-07-17 12:25 UTC by hanwu85

2023-08-03 18:04 UTC, richar983 requested changes

2023-08-03 18:04 UTC, richar983 commented on wca-guidelines.md
> +- B2f+) [釐清] 因為解方塊階段開始時，參賽者要自行打開蓋子，所以還原開始之前，參賽者不能碰觸蓋子的處罰不適用 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
```suggestion
- B2f+) [釐清] 因為解方塊階段開始時參賽者必須自行打開蓋子，因此不適用還原開始前，參賽者不能碰觸蓋子的處罰 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
```

2023-08-03 18:04 UTC, richar983 commented on wca-guidelines.md
>  - B1+) [提醒] 參賽者禁止使用有顆粒、記號或是其他可區分各部位特徵的方塊。(參見[規則 3k](regulations:regulation:3k))盲解項目時應該要特別留意此事。
```suggestion
- B1+) [提醒] 參賽者禁止使用有Logo (參見[規則 3i](regulations:regulation:3l))、顆粒、記號或是其他可區分各部位特徵的方塊 (參見[規則 3k](regulations:regulation:3k))。盲解項目時應該要特別留意此事。
```

此處 2023-02-01 版本已更新，似乎遺漏更新了！

此外，稍微微調了第二個"參見"的位置... 但是我去搜尋了整個中文版本，發現好像大多數的參見都是放在句號後面。
但此處因為句號後面還有下一句話，會變成跟下一句話連在一起....
可能要考慮下怎麼樣比較好？

※ 下方 B2f+ 則是放在句號前沒錯。

2023-08-04 02:48 UTC, hanwu85 commented on wca-guidelines.md
> +- B2f+) [釐清] 因為解方塊階段開始時，參賽者要自行打開蓋子，所以還原開始之前，參賽者不能碰觸蓋子的處罰不適用 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
這邊不該用`必須`這個字，必須不必須 不是這裡的重點。
我的建議

`因為解方塊階段開始時參賽者會自行打開蓋子，因此不適用還原開始前，參賽者不能碰觸蓋子的處罰`

2023-08-04 03:04 UTC, hanwu85 commented on wca-guidelines.md
>  - B1+) [提醒] 參賽者禁止使用有顆粒、記號或是其他可區分各部位特徵的方塊。(參見[規則 3k](regulations:regulation:3k))盲解項目時應該要特別留意此事。
原文：The competitor must use a puzzle without logos (see [Regulation 3l](https://www.worldcubeassociation.org/regulations/#3l)), textures, markings, or other features that distinguish similar pieces (see [Regulation 3k](https://www.worldcubeassociation.org/regulations/#3k)). This should be given special attention for Blindfolded Solving.

2023-08-04 03:06 UTC, hanwu85 commented
參見擺句號前句號後 可以在style guide裡面討論
先以翻譯上線為主

2023-08-04 04:15 UTC, richar983 commented on wca-guidelines.md
> +- B2f+) [釐清] 因為解方塊階段開始時，參賽者要自行打開蓋子，所以還原開始之前，參賽者不能碰觸蓋子的處罰不適用 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
同意，那這樣子我認為 `要自行打開` 可能會好過 `會自行打開`

```suggestion
- B2f+) [釐清] 因為解方塊階段開始時參賽者要自行打開蓋子，因此不適用還原開始前參賽者不能碰觸蓋子的處罰 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
```

2023-08-04 04:18 UTC, richar983 requested changes

2023-08-04 04:18 UTC, richar983 commented on wca-guidelines.md
> +- B2f+) [釐清] 因為解方塊階段開始時，參賽者要自行打開蓋子，所以還原開始之前，參賽者不能碰觸蓋子的處罰不適用 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
同意，那這樣子我認為 `要自行打開` 可能會好過 `會自行打開`

```suggestion
- B2f+) [釐清] 因為解方塊階段開始時參賽者要自行打開蓋子，因此不適用還原開始前參賽者不能碰觸蓋子的處罰 (參見 [規則 B2b](regulations:regulation:B2b) 和 [規則 B2c](regulations:regulation:B2c))。
```

其次是我又稍微琢磨了一下，我發現第二個逗點也可以省略掉。不然太快斷句了。


(題外話：原來要在正確的地方輸入review的內容，才有辦法完成PR中的review require )

2023-08-05 10:55 UTC, richar983 approved these changes

2023-08-05 13:37 UTC, merged