更新規則5
hanwu85/WCA-TC-2023_Open pull request #20
Opened 2023-07-18 14:36 UTC by hanwu85

2023-08-03 18:39 UTC, richar983 requested changes

2023-08-03 18:39 UTC, richar983 commented on wca-regulations.md
> +        - 5b5f) 如果一個零件半分離或是沒有完全歸位，考慮方塊的現有狀態，這個零件的最終位置被視為一般正常機構運作下最在方塊中接近的位置。如果最終的位置會讓方塊解完成，這個零件不被視為被方塊故障影響。
```suggestion
        - 5b5f) 如果一個零件部分分離或是未完全歸位，考慮方塊當下的狀態，這個零件的最終位置將被視為一般正常情況下最接近的位置。如果最終的位置能讓方塊成功還原，則這個零件不被視為方塊故障。
```

這條超級難翻譯，或許需要以整條改寫成符合中文敘述的句子。
請反覆閱讀我提出的建議句子...  希望在該翻譯到的部分都有翻譯到且符合意境？
若有遺漏或建議，不吝指教xDD

2023-08-03 18:39 UTC, richar983 commented on wca-regulations.md
> +    - 5b6) 定義：一個零件是一個或是多個連結在一起的部件群，且在一般操作下跟其他零件沒有相對的移動關係。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的頂部件、少一個角塊蓋的3x3x3方塊角塊，一個3x3x3方塊的角塊蓋）。
```suggestion
    - 5b6) 定義：一個零件是指一個或多個在正常操作下，保持結合且與其他零件不會相對移動的零件。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的角塊、少一片角塊蓋的3x3x3方塊角塊、一片3x3x3方塊的角塊蓋）。
```

`是指一個或多個在正常操作下，保持結合且與其他零件沒有相對移動關係的零件`

這條也超級難翻譯跟理解，一樣請指教提點xDD
光是規則五就想了超過半小時Orzz

2023-08-04 14:21 UTC, hanwu85 commented on wca-regulations.md
> +    - 5b6) 定義：一個零件是一個或是多個連結在一起的部件群，且在一般操作下跟其他零件沒有相對的移動關係。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的頂部件、少一個角塊蓋的3x3x3方塊角塊，一個3x3x3方塊的角塊蓋）。
理查大大 comment的好像比較通順XD
```suggestion
    - 5b6) 定義：是指一個或多個在正常操作下，保持結合且與其他零件沒有相對移動關係的零件。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的角塊、少一片角塊蓋的3x3x3方塊角塊、一片3x3x3方塊的角塊蓋）。
```

2023-08-05 10:58 UTC, richar983 commented on wca-regulations.md
> +    - 5b6) 定義：一個零件是一個或是多個連結在一起的部件群，且在一般操作下跟其他零件沒有相對的移動關係。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的頂部件、少一個角塊蓋的3x3x3方塊角塊，一個3x3x3方塊的角塊蓋）。
關於吳翰大大這個5b6的開頭，是不是要先寫出哪個部分？ `一個零件` ，因為只寫 `是指` 好像有點奇怪？沒有主詞？！

2023-08-05 13:49 UTC, hanwu85 commented on wca-regulations.md
> +    - 5b6) 定義：一個零件是一個或是多個連結在一起的部件群，且在一般操作下跟其他零件沒有相對的移動關係。（例如：一個3x3x3方塊的中心蓋、一個金字塔Pyraminx的頂部件、少一個角塊蓋的3x3x3方塊角塊，一個3x3x3方塊的角塊蓋）。
copy漏掉了 哈

2023-08-05 18:33 UTC, richar983 approved these changes
5b6要記得更新到檔案內哦xDDD

2023-08-06 05:16 UTC, merged