更新規則9
hanwu85/WCA-TC-2023_Open pull request #22
Opened 2023-07-18 14:56 UTC by hanwu85

2023-08-03 17:58 UTC, richar983 requested changes

2023-08-03 17:58 UTC, richar983 commented on wca-regulations.md
> +        - 9f4a) 如果很明顯一位參賽者違反規則到要被取消該次還原成績，裁判應該要立即停止那次還原。如果裁判不確定或是可能會造成不小的爭議（例如：額外還原機會會造成比賽延遲），裁判應該要諮詢WCA代表。    - 9f5) 如果參賽者放棄比賽中某次還原機會，則該次成績記錄為DNS（未開始）。
```suggestion
        - 9f4a) 如果很明顯一位參賽者違反規則到要被取消該次還原成績，裁判應該要立即停止那次還原。如果裁判不確定或是可能會造成不小的爭議（例如：額外還原機會會造成比賽延遲），裁判應該要諮詢WCA代表。    
        - 9f5) 如果參賽者放棄比賽中某次還原機會，則該次成績記錄為DNS（未開始）。
```

這裡換行失誤！

2023-08-03 17:58 UTC, richar983 commented on wca-regulations.md
> +        - 9u2a) 所有比賽列出的WCA代表已離開且再回來比賽場地。
```suggestion
        - 9u2a) 所有比賽列出的WCA代表已離開比賽場地。
```

為什麼會 `再回來` ????? XDDD

2023-08-04 02:39 UTC, hanwu85 commented on wca-regulations.md
> +        - 9u2a) 所有比賽列出的WCA代表已離開且再回來比賽場地。
少打一個字啦

2023-08-04 02:40 UTC, hanwu85 commented on wca-regulations.md
> +        - 9u2a) 所有比賽列出的WCA代表已離開且再回來比賽場地。
```suggestion
        - 9u2a) 所有比賽列出的WCA代表已離開且不會再回來比賽場地。
```

2023-08-04 04:41 UTC, richar983 commented on wca-regulations.md
> +        - 9u2a) 所有比賽列出的WCA代表已離開且再回來比賽場地。
這樣我覺得OK，不過好像尚未更改上去？要確認下再approve

2023-08-04 07:14 UTC, hanwu85 commented on wca-regulations.md
> +        - 9u2a) 所有比賽列出的WCA代表已離開且再回來比賽場地。
那就直接修改了

2023-08-05 18:35 UTC, richar983 approved these changes

2023-08-06 05:16 UTC, merged