更新規則11
hanwu85/WCA-TC-2023_Open pull request #23
Opened 2023-07-18 15:00 UTC by hanwu85

2023-08-03 17:50 UTC, richar983 requested changes

2023-08-03 17:50 UTC, richar983 commented on wca-regulations.md
> +- 11e) WCA代表可以給予因意外事件而影響參賽者額外的還原機會。在意外事件發生後該次還原完成前，參賽者應該以口頭或文字向裁判及WCA代表申訴，才能獲得額外的還原機會。上訴並不保證有效。
```suggestion
- 11e) WCA代表可以給予參賽者額外的還原機會，用來替代因意外事件造成影響的還原。參賽者應該要在意外事件發生後，且該次還原完成前，以口頭或文字向裁判及WCA代表申訴，才能獲得額外的還原機會。申訴並不保證可以獲得額外的還原機會。
```

最後一節的 `上訴` 可以考慮改成 `申訴` ，因為前面也都是提及 `申訴`

此外也大致上的修改了一下句子的結構，因為原始的中文結構我個人覺得有點難以閱讀，並修正程更趨近於英文版本的敘述方式，雖然攏長但是可能更簡單明確？

2023-08-04 13:07 UTC, hanwu85 commented on wca-regulations.md
> +- 11e) WCA代表可以給予因意外事件而影響參賽者額外的還原機會。在意外事件發生後該次還原完成前，參賽者應該以口頭或文字向裁判及WCA代表申訴，才能獲得額外的還原機會。上訴並不保證有效。
OK!

2023-08-05 18:50 UTC, richar983 approved these changes

2023-08-06 05:16 UTC, merged