更新附則A
hanwu85/WCA-TC-2023_Open pull request #27
Opened 2023-07-19 04:44 UTC by hanwu85

2023-08-03 15:08 UTC, richar983 requested changes

2023-08-03 15:08 UTC, richar983 commented on wca-regulations.md
> +        - A3c2) 當蓋子拿起時，如果方塊並沒有對齊，參賽者可以使其對齊，但僅限於[規則 10f](regulations:regulation:10f)所提的界限內。
```suggestion
        - A3c2) 當蓋子打開時，如果方塊並沒有對齊，參賽者可以將它對齊，但僅限於[規則 10f](regulations:regulation:10f)所提及的限度內。
```
1. 開頭的「拿起」或許改成「打開」...  且建議是否在  開蓋子 的這個動作都修正為「打開」呢？
2. 「使其」 或許可以修正為 「自己將它」「將它」「把它」
3. 最後的「限度」修正同步 10f 的用詞。

2023-08-03 15:08 UTC, richar983 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
請問這個部分的意思是，他不小心轉到也沒關係嗎.......

2023-08-03 15:08 UTC, richar983 commented on wca-regulations.md
> +    - A5a) 在觀察或是解方塊當中，參賽者禁止與裁判和WCA代表以外的人交談。處罰：判定該次還原未完成（DNF）。例外：如果參賽者沒有因與裁判和WCA代表以外的人交談而得利，成績可以被保留，由WCA代表決定。
備註：此處 2023-08-01 版本更新

此處使用「交談」，規則E5 使用「交流」   或許應該要同步？

2023-08-04 02:05 UTC, hanwu85 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
就是因為Square-1 容易不小心轉到的關係....
不是正方形的關係 觀察拿起來很容易不小心轉到

2023-08-04 02:06 UTC, hanwu85 commented on wca-regulations.md
> +    - A5a) 在觀察或是解方塊當中，參賽者禁止與裁判和WCA代表以外的人交談。處罰：判定該次還原未完成（DNF）。例外：如果參賽者沒有因與裁判和WCA代表以外的人交談而得利，成績可以被保留，由WCA代表決定。
全部merge完後 一次全部修正

2023-08-04 04:23 UTC, richar983 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
我的疑問是，A3c5部分，  `不應該被任何 10f 中記載的 非物議轉動 受罰`

10f 在 SQ指的是  UD最大45度  /最大90度

所以，他在觀察的時候是可以不小心轉超過這個限度的嗎？

`因為參賽者不應該被 "這個限度" 的非故意轉動除罰`？


這是我看了比較難以理解的部分xD

2023-08-04 04:24 UTC, richar983 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
我的疑問是，A3c5部分， 不應該被任何 10f 中記載的 非物議轉動 受罰

10f 在 SQ指的是 UD最大45度 /最大90度

所以，他在觀察的時候是可以不小心轉超過這個限度的嗎？

因為參賽者不應該被 "這個限度" 的非故意轉動除罰？

這是我看了比較難以理解的部分xD

2023-08-04 14:29 UTC, hanwu85 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
還是不能轉超過限度的
`should not be penalized for any accidental move made within the limits of Regulation 10f`

A3C1說
`The competitor must not apply moves or intentional changes in alignment during inspection.`
所以你連轉45度以內都不行 `" intentional changes in alignment during inspection"`
原本對齊的  你故意轉不對齊40度   這是不行的 (雖然沒達到一步)

但SQ1  最容易被轉動 不小心讓他不對齊 
由於轉動時無法分辨是不是 故意的
所以加了這一條
這是當初的用意
(我的印象是這樣啦)

當然後面說 `within the limits of Regulation 10f`
也就是說  不管你是不是非故意  超過  45 degrees (U/D) or 90 degrees (/)  就是DNF

2023-08-05 19:18 UTC, richar983 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
所以，言下之意就是，如果選手故意"不小心"轉動了30度 (小邊)，仍然是不會受到處罰的？
因為尚未超過規定的45度。以上正確嗎？

因為沒有辦法判斷他是不是"故意"的


因此，這個部分就是特別強調，當參賽者若"不慎"在SQ項目"不小心"轉了 45度以內，都是不會被處罰的！ 對嗎xDDDD

---

如果以上認知正確，那麼我嘗試著用中文的思維來寫這條規則，請參考一下xDD

原文：
`For Square-1, the competitor should not be penalized for any accidental move made within the limits of Regulation 10f.`

重新檢視原文並拆解
`參賽者不應該被處罰` `在任何偶然不小心的移動` `在10f的限制內製造`


原中文翻譯
`在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。`


我的建議
```suggestion
        - A3c5) 在Square-1項目，參賽者不應該在[規則 10f](regulations:regulation:10f)所描述的限度內，發生任何不小心的轉動而受到處罰。。
```

`should not` 按照翻譯習慣，翻譯為 `不應該`
`within 規則 10f 的 limit` 按照 `10e1` 的中文翻譯，翻譯為 `所描述的限度內`
`any accidental move` 翻作 `任何不小心的轉動`
`made` 可能翻譯成 `發生` 比較好連接前後句子..

2023-08-05 19:23 UTC, richar983 requested changes

2023-08-05 19:23 UTC, richar983 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
所以，言下之意就是，如果選手故意"不小心"轉動了30度 (小邊)，仍然是不會受到處罰的？
因為尚未超過規定的45度。以上正確嗎？

因為沒有辦法判斷他是不是"故意"的


因此，這個部分就是特別強調，當參賽者若"不慎"在SQ項目"不小心"轉了 45度以內，都是不會被處罰的！ 對嗎xDDDD

---

如果以上認知正確，那麼我嘗試著用中文的思維來寫這條規則，請參考一下xDD

原文：
`For Square-1, the competitor should not be penalized for any accidental move made within the limits of Regulation 10f.`

重新檢視原文並拆解
`參賽者不應該被處罰` `在任何偶然不小心的移動` `在10f的限制內製造`


原中文翻譯
`在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。`


我的建議
```suggestion
        - A3c5) 在Square-1項目，參賽者不應該在[規則 10f](regulations:regulation:10f)所描述的限度內，發生任何不小心的轉動而受到處罰。
```

`should not` 按照翻譯習慣，翻譯為 `不應該`
`within 規則 10f 的 limit` 按照 `10e1` 的中文翻譯，翻譯為 `所描述的限度內`
`any accidental move` 翻作 `任何不小心的轉動`
`made` 可能翻譯成 `發生` 比較好連接前後句子..


(結果這題也很難xDD 一個不小心就花了快半小時。)

2023-08-06 05:26 UTC, hanwu85 commented on wca-regulations.md
> +        - A3c5) 在Square-1項目，參賽者不應該被任何[規則 10f](regulations:regulation:10f)中記載的非故意轉動受罰。
感覺不錯
但最後一句有點不通順，我把 `發生` 改成 `因`  看看感覺如何?
```suggestion
        - A3c5) 在Square-1項目，參賽者不應該在[規則 10f](regulations:regulation:10f)所描述的限度內，因任何不小心的轉動而受到處罰。
```

2023-08-06 05:27 UTC, hanwu85 commented on wca-regulations.md
> +    - A5a) 在觀察或是解方塊當中，參賽者禁止與裁判和WCA代表以外的人交談。處罰：判定該次還原未完成（DNF）。例外：如果參賽者沒有因與裁判和WCA代表以外的人交談而得利，成績可以被保留，由WCA代表決定。
#29  交流的issue在這

2023-08-06 19:14 UTC, richar983 approved these changes

2023-08-07 02:20 UTC, merged