更新附則B
hanwu85/WCA-TC-2023_Open pull request #28
Opened 2023-07-19 05:14 UTC by hanwu85

2023-08-03 15:06 UTC, richar983 requested changes

2023-08-03 15:06 UTC, richar983 commented on wca-regulations.md
> +    - B1a) 沒有觀察階段。（也就是還原階段和解方塊階段為同時開始）
待修正

2023-08-03 15:06 UTC, richar983 commented on wca-regulations.md
> +    - B1a) 沒有觀察階段。（也就是還原階段和解方塊階段為同時開始）
```suggestion
    - B1a) 沒有觀察階段。（也就是還原階段開始時沒有觀察階段直接開始解方塊階段）
```

這個句子有點陷入 Attempt 和 Solve 翻譯成中文上用詞的混亂了...
但由於大版本更新過後，可能會針對用詞進行第二波的修正，因此這個部分可能就先大概大概的帶過？

以上建議為更清晰的表示這個括號內所要表示的內容，雖然可能不如英文版本直白，但應該會更好理解。

2023-08-03 15:06 UTC, richar983 commented on wca-regulations.md
> +	- B5a1) 如果除了Stackmat計時器以外還用了碼錶，當參賽者結束解方塊階段時，裁判要迅速停下碼錶。
```suggestion
	- B5a1) 如果除了Stackmat計時器以外還使用了碼錶計時，當參賽者結束解方塊階段時，裁判要迅速停下碼錶。
```

2023-08-04 01:45 UTC, hanwu85 commented on wca-regulations.md
> +    - B1a) 沒有觀察階段。（也就是還原階段和解方塊階段為同時開始）
OK, 同意  之後再好好討論 attempt 跟solve的翻譯

2023-08-04 04:24 UTC, richar983 approved these changes

2023-08-04 07:12 UTC, merged