更新附則E
hanwu85/WCA-TC-2023_Open pull request #30
Opened 2023-07-19 05:26 UTC by hanwu85

2023-07-19 18:40 UTC, richar983 requested changes
soltion sheet > 解答用紙 > 答案卷  ??

備註：
  E3a 為 2023-08-01 版本修正
  E5 為 2023-02-01 版本修正

2023-07-19 18:40 UTC, richar983 commented on wca-regulations.md
> +    - E3a) 紙（由裁判提供）、解答用紙（由裁判提供）、該次還原的轉亂狀態圖片（可以是在紙或是解答用紙上）和筆或類似書寫用文具（由裁判提供，或自行準備）。
```suggestion
    - E3a) 紙（由裁判提供）、答案卷（由裁判提供）、該次還原的轉亂圖示（可能在紙或答案卷上）和筆或類似書寫用的文具（由裁判提供，或自行準備）。
```

本建議重點：
  解答用紙 > 答案卷    可能比較實際點..?
  原文為：Solution sheet

  但若這麼修改，Paper 就要翻譯成白紙或是保留"紙"可能就得考慮一下...

2023-07-19 18:40 UTC, richar983 commented on wca-regulations.md
> +- E5) 參賽者禁止與WCA代表或是裁判以外的人交流。交流的內容應該關於WCA競賽規則，參賽者禁止獲得解法的協助。處罰：判定該次還原未完成（DNF）。
```suggestion
- E5) 參賽者禁止與WCA代表或裁判以外的人進行交流。交流的內容應該要關於WCA競賽規則，且參賽者不得從中獲得解法的協助。處罰：判定該次還原未完成（DNF）。
```

口語修正？

2023-07-23 11:08 UTC, hanwu85 commented on wca-regulations.md
> +    - E3a) 紙（由裁判提供）、解答用紙（由裁判提供）、該次還原的轉亂狀態圖片（可以是在紙或是解答用紙上）和筆或類似書寫用文具（由裁判提供，或自行準備）。
`解答用紙`改成`答案卷` OK
paper的翻譯維持 `紙`我覺得不受影響

原文: `....a picture of the scramble for that attempt (which may be included on the paper or solution sheet),..`
所以是 `可以是在紙或是答案卷上`

2023-07-23 11:10 UTC, hanwu85 commented
交談-交流 誤翻譯 已加入issue 
#29

2023-08-03 14:56 UTC, richar983 approved these changes

2023-08-03 14:57 UTC, richar983 requested changes

2023-08-03 14:57 UTC, richar983 commented on wca-regulations.md
> +    - E3a) 紙（由裁判提供）、解答用紙（由裁判提供）、該次還原的轉亂狀態圖片（可以是在紙或是解答用紙上）和筆或類似書寫用文具（由裁判提供，或自行準備）。
同意，那就是  答案卷 跟 紙。

2023-08-04 04:27 UTC, richar983 approved these changes

2023-08-04 07:12 UTC, merged