Time Limit
hanwu85/WCA-TC-2023_Open pull request #38
Opened 2023-08-08 12:05 UTC by hanwu85

2023-08-08 12:59 UTC, richar983 requested changes

2023-08-08 12:59 UTC, richar983 commented on wca-guidelines.md
> +- A1a2+) [附加] 如果是累積時間限制，裁判應記下DNF並用括號備註原始時間，例如：DNF (1:02.27)。
```suggestion
- A1a2+) [附加] 如果是使用累積時間限制，裁判應記下DNF並用括號備註原始時間，例如：DNF (1:02.27)。
```

2023-08-08 12:59 UTC, richar983 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪比賽只使用了設置30分鐘的累積時間限制，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是
```suggestion
- A1a2++) [舉例] 如果某一輪比賽只設置30分鐘的累積時間限制，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是如果第三次還原是13:59 + 2 = 14:01的時候則沒有符合時間限制。
```

目前算式中，看起來都有空格，算式前應該就不用空格了嗎？！

2023-08-08 12:59 UTC, richar983 commented on wca-guidelines.md
> +- E2b+) [釐清] 參賽者可以在時間限制以前交出解法來提早結束。
```suggestion
- E2b+) [釐清] 參賽者可以在時間限制結束以前交出解法，來提早結束此次還原。
```

這題要思考一下？

2023-08-08 12:59 UTC, richar983 commented on wca-regulations.md
> +        - A1a1) 一般默認的單次時間限制是10分鐘，但主辦團隊可以公告較久或較短的時間限制。某一輪中的每一次時間限制必須要相同。
```suggestion
        - A1a1) 一般預設的單次時間限制是10分鐘，但主辦團隊可以公告較久或較短的時間限制。某一輪中的每一次時間限制必須要相同。
```
改`預設`台式用詞xDDD

2023-08-08 12:59 UTC, richar983 commented on wca-regulations.md
> +        - A1a2) 最少步數解和3x3x3多顆盲解以外的比賽項目，主辦團隊可以採用累積時間限制，累積時間限制必須適用於一輪中所有的還原（例如：3次還原的累積時間限制須低於20分鐘），或是不同比賽項目所有還原的時間總和。在這情況下，某一次還原的時間限制就是設定的時間限制或是累積時間限制減掉已用掉的還原時間總和，之中較短的時間。(參見[規則 A1a5](regulations:regul
```suggestion
        - A1a2) 最少步數解和3x3x3多顆盲解以外的比賽項目，主辦團隊可以採用累積時間限制，累積時間限制必須適用於一輪中所有的還原（例如：3次還原的累積時間限制須低於20分鐘），或是不同比賽項目所有還原的時間總和。在這情況下，某一次還原的時間限制就是設定的單次時間限制或是累積時間限制減掉已用掉的還原時間總和，之中較短的時間。(參見[規則 A1a5](regulations:regulation:A1a5))。若某一輪比賽有累積時間限制，必須只有一種累積時間限制。
```

2023-08-08 14:17 UTC, hanwu85 commented on wca-guidelines.md
> +- A1a2++) [舉例] 如果某一輪比賽只使用了設置30分鐘的累積時間限制，而某參賽者的前兩次成績是6:00和DNF(10:00)，這樣第三次的時間限制就是 30:00 - 6:00 - 10:00 = 14:00。在這個舉例中，只計算最後的還原結果。所以，第三次還原是無判罰13:59的時候，符合時間限制(參見[規則 9f2](regulations:regulation:9f2)) ，但是
就是還沒統一 所以我才想改， 這個關於style的先擺著吧
先以上線為準?

2023-08-08 14:18 UTC, hanwu85 commented on wca-guidelines.md
> +- E2b+) [釐清] 參賽者可以在時間限制以前交出解法來提早結束。
理查大大的建議比較好

2023-08-08 14:22 UTC, hanwu85 commented on wca-regulations.md
> +        - A1a2) 最少步數解和3x3x3多顆盲解以外的比賽項目，主辦團隊可以採用累積時間限制，累積時間限制必須適用於一輪中所有的還原（例如：3次還原的累積時間限制須低於20分鐘），或是不同比賽項目所有還原的時間總和。在這情況下，某一次還原的時間限制就是設定的時間限制或是累積時間限制減掉已用掉的還原時間總和，之中較短的時間。(參見[規則 A1a5](regulations:regul
雖然跟原文不太一樣, 但這樣翻譯意思好像比較正確

2023-08-10 06:19 UTC, richar983 approved these changes

2023-08-10 12:11 UTC, merged