更新方針5
hanwu85/WCA-TC-2023_Open pull request #5
Opened 2023-07-16 08:37 UTC by hanwu85

2023-08-03 18:47 UTC, richar983 requested changes

2023-08-03 18:47 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f++) [舉例] 4x4x4一個邊塊在原位旋轉視為還原完成。
原位？ 原地？
旋轉？翻轉？

```suggestion
- 5b5f++) [舉例] 4x4x4一個邊塊在原地旋轉視為還原完成。
```

```suggestion
- 5b5f++) [舉例] 4x4x4一個邊塊在原位翻轉時，仍然被視為還原完成。
```

雖然原文沒有那麼攏長，但或許更符合語意？

2023-08-03 18:47 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
```suggestion
- 5b5f+++) [舉例] 一個被原位翻轉影響的角塊可視為放置在正確的位置，但放置在正確位置並不代表還原完成。
```

這也有點繞口...

2023-08-03 18:47 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f++) [舉例] 4x4x4一個邊塊在原位旋轉視為還原完成。
好，推翻我自己，感覺原始的 `在原位旋轉` 更好。

但如果可行，我還是傾向於把句子拆分兩句更明確

```suggestion
- 5b5f++) [舉例] 4x4x4一個邊塊在原位翻轉時，仍被視為還原完成。
```

2023-08-04 03:09 UTC, hanwu85 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
這一個不改成 "原地旋轉"嗎?

2023-08-04 04:33 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
因為我前面也是有點猶豫了，到底該 `原地` 還是 `原位` ，雖然說 `原地` 應該是比較符合口語也比較好理解的，`原位` 可能對於年紀比較小的小朋友在意會上會有盲區... 因為整個句子裡還有出現其他太多個 `位` 了...

此外，我還發現後面兩個字也有差異  `翻轉` `旋轉` ..

所以更傾向使用哪一個呢？這將同時影響 5b5f++ 和 5b5f+++

`原位旋轉`
`原位翻轉`

`原地旋轉`
`原地翻轉`

2023-08-04 13:09 UTC, hanwu85 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
我比較想用 原位旋轉

2023-08-05 18:30 UTC, richar983 requested changes

2023-08-05 18:30 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
那就用 `原位旋轉` 好了~

2023-08-05 18:30 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f++) [舉例] 4x4x4一個邊塊在原地旋轉視為還原完成。
```suggestion
- 5b5f++) [舉例] 4x4x4一個邊塊在原位旋轉視為還原完成。
```

2023-08-05 18:30 UTC, richar983 commented on wca-guidelines.md
> +- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
```suggestion
- 5b5f+++) [舉例] 一個被原位旋轉影響的角塊可視為處於正確的位置，但處於正確位置並不代表還原完成。
```

2023-08-06 19:12 UTC, richar983 approved these changes

2023-08-07 02:19 UTC, merged