更新方針11
hanwu85/WCA-TC-2023_Open pull request #8
Opened 2023-07-16 17:35 UTC by hanwu85

2023-08-03 17:07 UTC, richar983 requested changes

2023-08-03 17:07 UTC, richar983 commented on wca-guidelines.md
> +- 11e+++) [建議] 方塊解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```suggestion
- 11e+++) [建議] 解方塊完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```

```suggestion
- 11e+++) [建議] 方塊被解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```

2023-08-03 17:07 UTC, richar983 commented on wca-guidelines.md
> +- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個要求，應該先給予一個暫時的額外還原機會。
雖然英文是 claim ，但或許這地方翻譯成「申訴」是個選擇？

```suggestion
- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個申訴，應該先給予一個暫時的額外還原機會。
```

2023-08-03 17:07 UTC, richar983 commented on wca-guidelines.md
> +- 11e++++++) [附加] 額外的還原機會被視為是在原本的還原時完成。例如：如果有一輪是在1月21日，而參賽者在1月22日被給予額外的還原機會，該額外的還原機會被視為在1月21日完成。
```suggestion
- 11e++++++) [附加] 額外的還原機會被視為在原始還原發生的時間完成的。例如：如果原始那一輪是在1月21日，而參賽者在1月22日被給予額外的還原機會，該額外的還原機會被視為在1月21日完成。
```

2023-08-04 02:11 UTC, hanwu85 commented on wca-guidelines.md
> +- 11e+++) [建議] 方塊解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
突然發現這一段應該是   `解方塊階段完成後` (不論解完狀態)，而不是方塊成功solved了

2023-08-04 02:13 UTC, hanwu85 commented on wca-guidelines.md
> +- 11e+++) [建議] 方塊解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```suggestion
- 11e+++) [建議] 解方塊階段完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```

2023-08-04 02:17 UTC, hanwu85 commented on wca-guidelines.md
> +- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個要求，應該先給予一個暫時的額外還原機會。
改成 `訴求` 如何?

2023-08-04 04:12 UTC, richar983 commented on wca-guidelines.md
> +- 11e+++) [建議] 方塊解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
對齁.. 這裡指拍表結束後..  那應該是 `解方塊階段結束後` 或 `解方塊階段完成後`
但我認為 `結束` 會比較好一點....

```suggestion
- 11e+++) [建議] 解方塊階段結束後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
```

2023-08-04 07:01 UTC, hanwu85 commented on wca-guidelines.md
> +- 11e+++) [建議] 方塊解完成後，WCA代表應該要更慎重斟酌是否給予額外的還原機會。額外的還原機會應該只有在特殊情況下才能給予。
GOOD!

2023-08-05 18:56 UTC, richar983 commented on wca-guidelines.md
> +- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個要求，應該先給予一個暫時的額外還原機會。
我研究了一下 claim 這個單字，`聲稱` `宣稱` `主張` 好像也都可以被翻譯作為使用

所以來假設拼湊一下句子看看

`沒有時間調查這個要求`
`沒有時間調查這個訴求`
`沒有時間調查這個主張`

我想，如果其他用詞不是更佳選項，那應該如同吳翰大大提及的 `訴求` 是個不錯的選擇！

相比 `請求`  `要求` ， `訴求` 看起來是更符合 11e 原始的意境的！！

2023-08-06 05:31 UTC, hanwu85 commented on wca-guidelines.md
> +- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個要求，應該先給予一個暫時的額外還原機會。
```suggestion
- 11e+++++) [附加] 如果WCA代表在比賽中沒有時間調查這個訴求，應該先給予一個暫時的額外還原機會。
```

2023-08-06 19:13 UTC, richar983 approved these changes
待修正上11e+++++的訴求。

2023-08-07 02:19 UTC, merged